# Generated by Django 5.2 on 2025-05-17 18:18

import utils.db_field_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='alarms',
            field=models.JSONField(default=utils.db_field_utils.create_alarms_field_default),
        ),
    ]
