# Generated by Django 5.2 on 2025-05-27 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_alarms'),
        ('assets', '0004_alter_asset_fields_to_update'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='catch_up_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catching_up_apps', related_query_name='catching_up_app', to='django_celery_beat.intervalschedule'),
        ),
        migrations.AlterField(
            model_name='application',
            name='invoc_interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norm_speed_apps', related_query_name='norm_speed_app', to='django_celery_beat.intervalschedule'),
        ),
        migrations.AlterField(
            model_name='application',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', related_query_name='application', to='assets.asset'),
        ),
    ]
