# Generated by Django 5.2 on 2025-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_catch_up_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_ts',
            field=models.BigIntegerField(default=1742479200000, editable=False),
            preserve_default=False,
        ),
    ]
