# Generated by Django 5.2 on 2025-05-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_fields_to_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='asset_type',
        ),
    ]
