# Generated by Django 5.2 on 2025-05-27 22:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_type_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='fields_to_update',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
    ]
