# Generated by Django 5.2 on 2025-06-13 13:24

import django.db.models.deletion
import utils.db_field_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datatypes', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_totalizer', models.BooleanField(default=False)),
                ('is_rbe', models.BooleanField(default=False)),
                ('t_update', models.BigIntegerField(blank=True, default=None, null=True)),
                ('t_change', models.BigIntegerField(blank=True, default=None, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('alarms', models.JSONField(default=utils.db_field_utils.create_alarms_field_default)),
                ('health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('msg_health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('nd_health', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0)),
                ('t_nd_health_error', models.BigIntegerField(default=300000)),
                ('health_next_eval_ts', models.BigIntegerField(default=0)),
                ('max_rate_of_change', models.FloatField(default=1.0)),
                ('max_plausible_value', models.FloatField(default=1000000.0)),
                ('min_plausible_value', models.FloatField(default=-1000000.0)),
                ('ts_to_start_with', models.BigIntegerField(default=0)),
                ('last_reading_ts', models.BigIntegerField(blank=True, default=None, null=True)),
                ('created_ts', models.BigIntegerField(editable=False)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datatypes.datatype')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', related_query_name='datastream', to='devices.device')),
            ],
            options={
                'db_table': 'datastreams',
                'constraints': [models.UniqueConstraint(fields=('name', 'parent_id'), name='unique_name_device')],
            },
        ),
    ]
