# Generated by Django 5.2 on 2025-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastreams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastream',
            name='t_nd_health_error',
            field=models.BigIntegerField(default=300000),
        ),
    ]
