# Generated by Django 5.2 on 2025-05-17 18:18

import utils.db_field_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastreams', '0002_alter_datastream_t_nd_health_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='alarms',
            field=models.JSONField(default=utils.db_field_utils.create_alarms_field_default),
        ),
        migrations.AddField(
            model_name='datastream',
            name='nd_health',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Ok'), (2, 'Warning'), (3, 'Error')], default=0),
        ),
    ]
