# Generated by Django 5.2 on 2025-05-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastreams', '0003_datastream_alarms_datastream_nd_health'),
        ('devices', '0002_device_alarms_device_chld_health'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastream',
            name='device',
        ),
        migrations.AddField(
            model_name='datastream',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datastreams', related_query_name='datastream', to='devices.device'),
            preserve_default=False,
        ),
    ]
