# Generated by Django 5.2 on 2025-05-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastreams', '0004_remove_datastream_device_datastream_parent'),
        ('datatypes', '0001_initial'),
        ('devices', '0002_device_alarms_device_chld_health'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datastream',
            name='unique_name_device',
        ),
        migrations.AddConstraint(
            model_name='datastream',
            constraint=models.UniqueConstraint(fields=('name', 'parent_id'), name='unique_name_device'),
        ),
    ]
