# Generated by Django 5.2 on 2025-05-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastreams', '0005_remove_datastream_unique_name_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastream',
            old_name='is_active',
            new_name='is_enabled',
        ),
    ]
