# Generated by Django 5.2 on 2025-05-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafeeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafeed',
            old_name='last_reading_rts',
            new_name='last_reading_ts',
        ),
        migrations.RenameField(
            model_name='datafeed',
            old_name='rts_to_start_with',
            new_name='ts_to_start_with',
        ),
    ]
