# Generated by Django 5.2 on 2025-05-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafeeds', '0002_rename_last_reading_rts_datafeed_last_reading_ts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafeed',
            old_name='application',
            new_name='parent',
        ),
    ]
