# Generated by Django 5.2 on 2025-05-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_alarms'),
        ('datafeeds', '0003_rename_application_datafeed_parent'),
        ('datastreams', '0004_remove_datastream_device_datastream_parent'),
        ('datatypes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datafeed',
            name='unique_name_app',
        ),
        migrations.AddConstraint(
            model_name='datafeed',
            constraint=models.UniqueConstraint(fields=('name', 'parent_id'), name='unique_name_app'),
        ),
    ]
