# Generated by Django 5.2 on 2025-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeeds', '0004_remove_datafeed_unique_name_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafeed',
            name='df_type',
            field=models.CharField(choices=[('None', 'None'), ('Status', 'Status'), ('Current state', 'Current State'), ('State', 'State'), ('Steam loss', 'Steam Loss'), ('Water loss', 'Water Loss'), ('Energy loss', 'Energy Loss'), ('Steam savings', 'Steam Savings'), ('Water savings', 'Water Savings'), ('Energy savings', 'Energy Savings')], default='None'),
        ),
    ]
