# Generated by Django 5.2 on 2025-06-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeeds', '0005_alter_datafeed_df_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeed',
            name='is_derived',
            field=models.BooleanField(default=False),
        ),
    ]
