# Generated by Django 5.2 on 2025-06-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafeeds', '0006_datafeed_is_derived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafeed',
            name='is_derived',
        ),
    ]
