# Generated by Django 5.2 on 2025-05-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datafeeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfReading',
            fields=[
                ('pk', models.CompositePrimaryKey('datafeed_id', 'time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('time', models.BigIntegerField()),
                ('db_value', models.FloatField()),
                ('restored', models.BooleanField(default=False)),
                ('datafeed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datafeeds.datafeed')),
            ],
            options={
                'db_table': 'df_readings',
            },
        ),
        migrations.RunSQL(
            """
            SELECT create_hypertable('df_readings', 'time');
            """,
            reverse_sql="""
                DROP TABLE df_readings;
            """
        ),
    ]
