# Generated by Django 5.2 on 2025-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Temperature', 'Temp'), ('Pressure', 'Pres'), ('Mass', 'Mass'), ('Mass flowrate', 'Mass Flow'), ('Volumetric flowrate', 'Volum Flow'), ('Conductivity', 'Cond'), ('State', 'State'), ('Counts', 'Counts')], default='Temperature')),
                ('meas_units', models.CharField(choices=[('-', 'Dimensionless'), ('*C', 'Deg C'), ('barg', 'Barg'), ('kPa', 'Kpa'), ('kg', 'Kg'), ('kg/h', 'Kg H'), ('kg/s', 'Kg S'), ('m3/h', 'M3 H'), ('m3/s', 'M3 S'), ('uSm/cm', 'Usm Cm')], default='*C')),
                ('agg_type', models.IntegerField(choices=[(0, 'Avg'), (1, 'Sum'), (2, 'Last')], default=0)),
                ('var_type', models.IntegerField(choices=[(0, 'Continuous'), (1, 'Discrete'), (3, 'Nominal'), (4, 'Ordinal')], default=0)),
            ],
            options={
                'db_table': 'datatypes',
            },
        ),
    ]
