# Generated by Django 5.2 on 2025-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dimensionless')),
                ('meas_unit', models.CharField(blank=True, default='')),
                ('agg_type', models.IntegerField(choices=[(0, 'Avg'), (1, 'Sum'), (2, 'Last')], default=0)),
                ('var_type', models.IntegerField(choices=[(0, 'Continuous'), (1, 'Discrete'), (3, 'Nominal'), (4, 'Ordinal')], default=0)),
            ],
            options={
                'db_table': 'datatypes',
            },
        ),
    ]
