# Generated by Django 5.2 on 2025-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='meas_units',
        ),
        migrations.AddField(
            model_name='datatype',
            name='meas_unit',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(default='Dimensionless'),
        ),
    ]
