# Generated by Django 5.2 on 2025-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatypes', '0002_remove_datatype_meas_units_datatype_meas_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='meas_unit',
            field=models.CharField(blank=True, default=''),
        ),
    ]
